app_settings:
  app_type: "google_sheets" # only lowercase letters, numbers, and underscores are allowed, e.g. salesforce, sap, zoho_crm, etc.
  app_name: "Google Sheets"
  app_icon_svg_url: "https://upload.wikimedia.org/wikipedia/commons/3/30/Google_Sheets_logo_%282014-2020%29.svg" # icon of the app (SVG URL)
  app_description: "Google Sheets connector providing CRUD operations on spreadsheets"
  routes_directory: "src/modules" # directory where the modules are located

local_development_settings:
  sentry_dsn: ""
  cors_origins: ["*"]
  routes_directory: "src/modules"
  debug: true
  host: "0.0.0.0"
  port: 2003
